image: node:22.15.0-alpine

stages:
  - install
  - verify

variables:
  YARN_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/yarn'

.rules:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
    - if: ($CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push")
  interruptible: true

.cache_template: &cache_config
  key:
    files:
      - yarn.lock
  paths:
    - cache/yarn
    - node_modules
    - frontend/node_modules
    - backend/node_modules

install:
  stage: install
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - yarn.lock
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      changes:
        - yarn.lock
  cache:
    <<: *cache_config
    policy: push
  script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --ignore-engines

verify:
  stage: verify
  rules:
    - !reference [.rules, rules]
  cache:
    <<: *cache_config
    policy: pull
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn format:check
    - yarn lint
    - yarn frontend test
    - yarn backend test
    - yarn frontend build
    - yarn backend build
