version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: quacker
      MYSQL_USER: quackerUser
      MYSQL_PASSWORD: quackerPassword
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          'CMD',
          'mariadb-admin',
          'ping',
          '-uquackerUser',
          '-pquackerPassword',
        ]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 10s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
