/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedPagesRouteImport } from './routes/_ProtectedPages'
import { Route as ProtectedPagesIndexRouteImport } from './routes/_ProtectedPages/index'
import { Route as ProtectedPagesUsersUsernameRouteImport } from './routes/_ProtectedPages/users.$username'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesRoute = ProtectedPagesRouteImport.update({
  id: '/_ProtectedPages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesIndexRoute = ProtectedPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPagesRoute,
} as any)
const ProtectedPagesUsersUsernameRoute =
  ProtectedPagesUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => ProtectedPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedPagesIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/': typeof ProtectedPagesIndexRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ProtectedPages': typeof ProtectedPagesRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_ProtectedPages/': typeof ProtectedPagesIndexRoute
  '/_ProtectedPages/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/terms'
    | '/users/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/signup' | '/terms' | '/' | '/users/$username'
  id:
    | '__root__'
    | '/_ProtectedPages'
    | '/about'
    | '/login'
    | '/signup'
    | '/terms'
    | '/_ProtectedPages/'
    | '/_ProtectedPages/users/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedPagesRoute: typeof ProtectedPagesRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages': {
      id: '/_ProtectedPages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages/': {
      id: '/_ProtectedPages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesIndexRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_ProtectedPages/users/$username': {
      id: '/_ProtectedPages/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof ProtectedPagesUsersUsernameRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
  }
}

interface ProtectedPagesRouteChildren {
  ProtectedPagesIndexRoute: typeof ProtectedPagesIndexRoute
  ProtectedPagesUsersUsernameRoute: typeof ProtectedPagesUsersUsernameRoute
}

const ProtectedPagesRouteChildren: ProtectedPagesRouteChildren = {
  ProtectedPagesIndexRoute: ProtectedPagesIndexRoute,
  ProtectedPagesUsersUsernameRoute: ProtectedPagesUsersUsernameRoute,
}

const ProtectedPagesRouteWithChildren = ProtectedPagesRoute._addFileChildren(
  ProtectedPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedPagesRoute: ProtectedPagesRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
