/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedPagesRouteImport } from './routes/_ProtectedPages'
import { Route as ProtectedPagesIndexRouteImport } from './routes/_ProtectedPages/index'
import { Route as ProtectedPagesTermsRouteImport } from './routes/_ProtectedPages/terms'
import { Route as ProtectedPagesPractical01RouteImport } from './routes/_ProtectedPages/practical-01'
import { Route as ProtectedPagesAboutRouteImport } from './routes/_ProtectedPages/about'
import { Route as ProtectedPagesUsersUsernameRouteImport } from './routes/_ProtectedPages/users.$username'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesRoute = ProtectedPagesRouteImport.update({
  id: '/_ProtectedPages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesIndexRoute = ProtectedPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPagesRoute,
} as any)
const ProtectedPagesTermsRoute = ProtectedPagesTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ProtectedPagesRoute,
} as any)
const ProtectedPagesPractical01Route =
  ProtectedPagesPractical01RouteImport.update({
    id: '/practical-01',
    path: '/practical-01',
    getParentRoute: () => ProtectedPagesRoute,
  } as any)
const ProtectedPagesAboutRoute = ProtectedPagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedPagesRoute,
} as any)
const ProtectedPagesUsersUsernameRoute =
  ProtectedPagesUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => ProtectedPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedPagesIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof ProtectedPagesAboutRoute
  '/practical-01': typeof ProtectedPagesPractical01Route
  '/terms': typeof ProtectedPagesTermsRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof ProtectedPagesAboutRoute
  '/practical-01': typeof ProtectedPagesPractical01Route
  '/terms': typeof ProtectedPagesTermsRoute
  '/': typeof ProtectedPagesIndexRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ProtectedPages': typeof ProtectedPagesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_ProtectedPages/about': typeof ProtectedPagesAboutRoute
  '/_ProtectedPages/practical-01': typeof ProtectedPagesPractical01Route
  '/_ProtectedPages/terms': typeof ProtectedPagesTermsRoute
  '/_ProtectedPages/': typeof ProtectedPagesIndexRoute
  '/_ProtectedPages/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/about'
    | '/practical-01'
    | '/terms'
    | '/users/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/about'
    | '/practical-01'
    | '/terms'
    | '/'
    | '/users/$username'
  id:
    | '__root__'
    | '/_ProtectedPages'
    | '/login'
    | '/signup'
    | '/_ProtectedPages/about'
    | '/_ProtectedPages/practical-01'
    | '/_ProtectedPages/terms'
    | '/_ProtectedPages/'
    | '/_ProtectedPages/users/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedPagesRoute: typeof ProtectedPagesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages': {
      id: '/_ProtectedPages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages/': {
      id: '/_ProtectedPages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesIndexRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_ProtectedPages/terms': {
      id: '/_ProtectedPages/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ProtectedPagesTermsRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_ProtectedPages/practical-01': {
      id: '/_ProtectedPages/practical-01'
      path: '/practical-01'
      fullPath: '/practical-01'
      preLoaderRoute: typeof ProtectedPagesPractical01RouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_ProtectedPages/about': {
      id: '/_ProtectedPages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedPagesAboutRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_ProtectedPages/users/$username': {
      id: '/_ProtectedPages/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof ProtectedPagesUsersUsernameRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
  }
}

interface ProtectedPagesRouteChildren {
  ProtectedPagesAboutRoute: typeof ProtectedPagesAboutRoute
  ProtectedPagesPractical01Route: typeof ProtectedPagesPractical01Route
  ProtectedPagesTermsRoute: typeof ProtectedPagesTermsRoute
  ProtectedPagesIndexRoute: typeof ProtectedPagesIndexRoute
  ProtectedPagesUsersUsernameRoute: typeof ProtectedPagesUsersUsernameRoute
}

const ProtectedPagesRouteChildren: ProtectedPagesRouteChildren = {
  ProtectedPagesAboutRoute: ProtectedPagesAboutRoute,
  ProtectedPagesPractical01Route: ProtectedPagesPractical01Route,
  ProtectedPagesTermsRoute: ProtectedPagesTermsRoute,
  ProtectedPagesIndexRoute: ProtectedPagesIndexRoute,
  ProtectedPagesUsersUsernameRoute: ProtectedPagesUsersUsernameRoute,
}

const ProtectedPagesRouteWithChildren = ProtectedPagesRoute._addFileChildren(
  ProtectedPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedPagesRoute: ProtectedPagesRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
