/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicLayoutRouteImport } from './routes/_PublicLayout'
import { Route as ProtectedPagesRouteImport } from './routes/_ProtectedPages'
import { Route as ProtectedPagesIndexRouteImport } from './routes/_ProtectedPages/index'
import { Route as PublicLayoutTermsRouteImport } from './routes/_PublicLayout/terms'
import { Route as PublicLayoutPractical01RouteImport } from './routes/_PublicLayout/practical-01'
import { Route as PublicLayoutAboutRouteImport } from './routes/_PublicLayout/about'
import { Route as ProtectedPagesUsersUsernameRouteImport } from './routes/_ProtectedPages/users.$username'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_PublicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesRoute = ProtectedPagesRouteImport.update({
  id: '/_ProtectedPages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesIndexRoute = ProtectedPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPagesRoute,
} as any)
const PublicLayoutTermsRoute = PublicLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutPractical01Route = PublicLayoutPractical01RouteImport.update({
  id: '/practical-01',
  path: '/practical-01',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutAboutRoute = PublicLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ProtectedPagesUsersUsernameRoute =
  ProtectedPagesUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => ProtectedPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedPagesIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof PublicLayoutAboutRoute
  '/practical-01': typeof PublicLayoutPractical01Route
  '/terms': typeof PublicLayoutTermsRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedPagesIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof PublicLayoutAboutRoute
  '/practical-01': typeof PublicLayoutPractical01Route
  '/terms': typeof PublicLayoutTermsRoute
  '/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ProtectedPages': typeof ProtectedPagesRouteWithChildren
  '/_PublicLayout': typeof PublicLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_PublicLayout/about': typeof PublicLayoutAboutRoute
  '/_PublicLayout/practical-01': typeof PublicLayoutPractical01Route
  '/_PublicLayout/terms': typeof PublicLayoutTermsRoute
  '/_ProtectedPages/': typeof ProtectedPagesIndexRoute
  '/_ProtectedPages/users/$username': typeof ProtectedPagesUsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/about'
    | '/practical-01'
    | '/terms'
    | '/users/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/about'
    | '/practical-01'
    | '/terms'
    | '/users/$username'
  id:
    | '__root__'
    | '/_ProtectedPages'
    | '/_PublicLayout'
    | '/login'
    | '/signup'
    | '/_PublicLayout/about'
    | '/_PublicLayout/practical-01'
    | '/_PublicLayout/terms'
    | '/_ProtectedPages/'
    | '/_ProtectedPages/users/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedPagesRoute: typeof ProtectedPagesRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_PublicLayout': {
      id: '/_PublicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages': {
      id: '/_ProtectedPages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages/': {
      id: '/_ProtectedPages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesIndexRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
    '/_PublicLayout/terms': {
      id: '/_PublicLayout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicLayoutTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_PublicLayout/practical-01': {
      id: '/_PublicLayout/practical-01'
      path: '/practical-01'
      fullPath: '/practical-01'
      preLoaderRoute: typeof PublicLayoutPractical01RouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_PublicLayout/about': {
      id: '/_PublicLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicLayoutAboutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_ProtectedPages/users/$username': {
      id: '/_ProtectedPages/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof ProtectedPagesUsersUsernameRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
  }
}

interface ProtectedPagesRouteChildren {
  ProtectedPagesIndexRoute: typeof ProtectedPagesIndexRoute
  ProtectedPagesUsersUsernameRoute: typeof ProtectedPagesUsersUsernameRoute
}

const ProtectedPagesRouteChildren: ProtectedPagesRouteChildren = {
  ProtectedPagesIndexRoute: ProtectedPagesIndexRoute,
  ProtectedPagesUsersUsernameRoute: ProtectedPagesUsersUsernameRoute,
}

const ProtectedPagesRouteWithChildren = ProtectedPagesRoute._addFileChildren(
  ProtectedPagesRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutAboutRoute: typeof PublicLayoutAboutRoute
  PublicLayoutPractical01Route: typeof PublicLayoutPractical01Route
  PublicLayoutTermsRoute: typeof PublicLayoutTermsRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutAboutRoute: PublicLayoutAboutRoute,
  PublicLayoutPractical01Route: PublicLayoutPractical01Route,
  PublicLayoutTermsRoute: PublicLayoutTermsRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedPagesRoute: ProtectedPagesRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
